{% set version = "2.4.4" %}
{% set build_number = 0 %}

{% set jpeg_version = os.environ.get('JPEG_VERSION', '9')|string %}
{% set libpng_version = os.environ.get('LIBPNG_VERSION', '1.6.21').replace('"','')|string %}
{% set build_string = "py{}_jpeg{}_libpng{}_{}".format(environ.get('CONDA_PY', ''), jpeg_version, libpng_version, build_number) %}

package:
  name: bob.io.image
  version: {{ version }}

source:
  fn: bob.io.image-{{ version }}.zip
  md5: a0331441e39dd6ae36babd83a1b399a5
  url: https://pypi.io/packages/source/b/bob.io.image/bob.io.image-{{ version }}.zip

build:
  number: {{ build_number }}
  string: {{ build_string }}
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base >=2.0.9
    - matplotlib
    - giflib 5.1.*
    - libpng {{ libpng_version }}
    - jpeg {{ jpeg_version }}*
    - libtiff 4.0.*
    - boost 1.61.*
    - cmake
    - pkg-config

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base >=2.0.9
    - matplotlib
    - giflib 5.1.*
    - libpng {{ libpng_version }}
    - jpeg {{ jpeg_version }}*
    - libtiff 4.0.*
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.io.image

  imports:
    - bob
    - bob.io
    - bob.io.image

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Image I/O support for Bob

extra:
  recipe-maintainers:
    - 183amir
